In [ ]:
!pip install stanza
!pip install cltk==0.1.121
!pip install pycaret
!pip install pyyaml==5.4.1

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 691 kB 8.4 MB/s 
     |████████████████████████████████| 216 kB 45.5 MB/s 
  Created wheel for emoji: filename=emoji-2.1.0-py3-none-any.whl size=212392 sha256=f77d968008393f0aa4dbc82e699f378755022071ebbdac11d9abcaaee2110ee8
  Stored in directory: /root/.cache/pip/wheels/77/75/99/51c2a119f4cfd3af7b49cc57e4f737bed7e40b348a85d82804
Successfully built emoji
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 625 kB 6.3 MB/s 
     |████████████████████████████████| 182 kB 44.7 MB/s 
     |████████████████████████████████| 965 kB 42.4 MB/s 
     |████████████████████████████████| 1.5 MB 50.8 MB/s 
     |████████████████████████████████| 468 kB 54.7 MB/s 
     |████████████████████████████████| 63 kB 1.8 MB/s 
  Created wheel for cltk: filename=cltk-0.1.121-py3-none-any.

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import stanza
import pandas as pd
from cltk.stop.marathi.stops import STOP_LIST as stop_words_marathi
import re
stanza.download('mr')
nlp = stanza.Pipeline('mr', processors='tokenize,pos,lemma,ner,mwt', verbose=True, use_gpu=True)

INFO:stanza:Downloading default packages for language: mr (Marathi) ...


INFO:stanza:Finished downloading models and saved to /root/stanza_resources.
INFO:stanza:Checking for updates to resources.json in case models have been updated.  Note: this behavior can be turned off with download_method=None or download_method=DownloadMethod.REUSE_RESOURCES


INFO:stanza:Loading these models for language: mr (Marathi):
| Processor | Package |
-----------------------
| tokenize  | ufal    |
| mwt       | ufal    |
| pos       | ufal    |
| lemma     | ufal    |
| ner       | l3cube  |

INFO:stanza:Use device: cpu
INFO:stanza:Loading: tokenize
INFO:stanza:Loading: mwt
INFO:stanza:Loading: pos
INFO:stanza:Loading: lemma
INFO:stanza:Loading: ner
INFO:stanza:Done loading processors!


In [ ]:
print(stop_words_marathi[:50])


['न', 'तरी', 'तो', 'हें', 'तें', 'कां', 'आणि', 'जें', 'जे', 'मग', 'ते', 'मी', 'जो', 'परी', 'गा', 'हे', 'ऐसें', 'आतां', 'तैसें', 'परि', 'नाहीं', 'तेथ', 'हा', 'तया', 'असे', 'म्हणे', 'काय', 'म्हणौनि', 'कीं', 'जैसें', 'तंव', 'तूं', 'होय', 'जैसा', 'आहे', 'पैं', 'तैसा,जरी', 'म्हणोनि,एक', 'ऐसा', 'जी', 'ना', 'मज', 'एथ', 'या', 'जेथ', 'जया', 'तुज', 'तेणें', 'तैं', 'पां']


In [ ]:
def preprocessing(input_text):
  
  input_text = re.sub('[-।,:?;!\(\)]','',input_text)
  input_text = " ".join(input_text.split())

  doc = nlp(input_text)
  """
  print("Word Segmentation and stopword removal")
  for i, sentence in enumerate(doc.sentences):
    print(f'====== Sentence {i+1} tokens =======')
    print(*[f'id: {token.id}\ttext: {token.text}' for token in sentence.tokens if token not in stop_words_marathi], sep='\n')
  
  print("\nPOS Tagging")
  print(*[f'word: {word.text}\tupos: {word.upos}\tfeats: {word.feats if word.feats else "_"}' for sent in doc.sentences for word in sent.words], sep='\n')
  #upos link: https://universaldependencies.org/u/pos/

  print("\nLemmatization")
  print(*[f'word: {word.text+" "}\tlemma: {word.lemma}' for sent in doc.sentences for word in sent.words], sep='\n')
  """
  #print(doc)
  for i, sentence in enumerate(doc.sentences):
    tokenized_text = [[token.id, token.text] for token in sentence.tokens]
  postagged_text = [[word.text,word.upos,word.feats] for sent in doc.sentences for word in sent.words]
  lemmatized_text = [[word.text,word.lemma] for sent in doc.sentences for word in sent.words]

  return tokenized_text, postagged_text, lemmatized_text

In [ ]:
def clean(text):
  text_lemma = []
  doc = nlp(text)
  lemma = []
  for sentence in doc.sentences:
      for word in sentence.words:
          text_lemma.append(word.lemma)
  text_lemma = " ".join(word for word in text_lemma)
  return text_lemma

In [ ]:
text = """यूएईने टीम इंडियाला संकटातून वाचवले, विश्वविजेत्या संघाला दुसऱ्या गटात पाठवले; पाहा सुधारित वेळापत्रक"""
tokenized_text, postagged_text, lemmatized_text = preprocessing(text)
print("\nTokenization")
for i in tokenized_text:
  print("ID: {0}\t Token: {1}".format(i[0],i[1]))
print("\nPOS Tagging")
for i in postagged_text:
  print("Word: {0}\t Universal POS: {1}\t Features: {2}".format(i[0],i[1],i[2]))
print("\nLemmatization")
for i in lemmatized_text:
  print("Word: {0}\t Lemma: {1}".format(i[0],i[1]))


Tokenization
ID: (1,)	 Token: यूएईने
ID: (2,)	 Token: टीम
ID: (3,)	 Token: इंडियाला
ID: (4,)	 Token: संकटातून
ID: (5,)	 Token: वाचवले
ID: (6, 6)	 Token: विश्वविजेत्या
ID: (7,)	 Token: संघाला
ID: (8,)	 Token: दुसऱ्या
ID: (9,)	 Token: गटात
ID: (10,)	 Token: पाठवले
ID: (11,)	 Token: पाहा
ID: (12,)	 Token: सुधारित
ID: (13,)	 Token: वेळापत्रक

POS Tagging
Word: यूएईने	 Universal POS: NOUN	 Features: Case=Erg|Gender=Masc|Number=Sing
Word: टीम	 Universal POS: PROPN	 Features: Case=Abs|Gender=Masc|Number=Sing
Word: इंडियाला	 Universal POS: NOUN	 Features: Case=Dat|Gender=Masc|Number=Sing
Word: संकटातून	 Universal POS: ADV	 Features: None
Word: वाचवले	 Universal POS: VERB	 Features: Aspect=Perf|Gender=Neut|Number=Sing|Person=3|VerbForm=Fin
Word: विश्विजजेया	 Universal POS: NOUN	 Features: Case=Abs|Gender=Masc|Number=Sing
Word: संघाला	 Universal POS: NOUN	 Features: Case=Dat|Gender=Masc|Number=Sing
Word: दुसऱ्या	 Universal POS: NUM	 Features: None
Word: गटात	 Universal POS: NOUN	 Features: Case

In [ ]:
print(clean(text))

यूएई टीम इंडिय संकटातून वाचवणे , विश्विजय संघ दुसरा गट पाठवणे ; पहाणे सुधारि वेळापत्रक


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score
import numpy as np
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
import pandas as pd

In [ ]:
df = pd.read_csv('news.csv')

X = df['headline']
y = df['label']
 
X_train, X_test, y_train, y_test = train_test_split(X,y ,
                                   random_state=104, 
                                   test_size=0.25, 
                                   shuffle=True)


In [ ]:
X_train_cleaned = X_train.map(lambda x: clean(x))
X_test_cleaned = X_test.map(lambda x: clean(x))

In [ ]:
X_train_cleaned[0]

'सचिन तेंडुलकरन बाई आठवणी देणे उजाळा'

In [ ]:
vectorizer = TfidfVectorizer()
X_train_Vectorized = vectorizer.fit_transform(X_train_cleaned)
X_test_Vectorized = vectorizer.transform(X_test_cleaned)


In [ ]:
import pickle
pickle.dump(vectorizer, open("vectorizer.pickle", "wb"))

In [ ]:
classifier = MultinomialNB()
classifier.fit(X_train_Vectorized, y_train)

MultinomialNB()

In [ ]:
Y_pred = classifier.predict(X_test_Vectorized)

In [ ]:
print('We got an accuracy of',np.mean(Y_pred == y_test)*100, '% over the test data.')

We got an accuracy of 77.0979743695742 % over the test data.


In [ ]:
cf_matrix = confusion_matrix(y_test,Y_pred)

print("Confusion Matrix \n",cf_matrix,"\n")
print("Accuracy is",round(accuracy_score(y_test,Y_pred),2)*100,"%")
print("F1 Score is",f1_score(y_test,Y_pred,average='weighted'))

Confusion Matrix 
 [[ 327    0  345]
 [  25   45  161]
 [  23    0 1493]] 

Accuracy is 77.0 %
F1 Score is 0.737052763119401


In [ ]:
import pickle
filename='classifier.pkl'
M=open(filename,'wb')
pickle.dump(classifier,M)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
M.close()

In [ ]:
!pip install gradio

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 5.3 MB 7.1 MB/s 
     |████████████████████████████████| 212 kB 26.2 MB/s 
     |████████████████████████████████| 112 kB 28.4 MB/s 
     |████████████████████████████████| 55 kB 3.3 MB/s 
     |████████████████████████████████| 84 kB 2.4 MB/s 
     |████████████████████████████████| 84 kB 2.8 MB/s 
     |████████████████████████████████| 2.3 MB 39.6 MB/s 
     |████████████████████████████████| 270 kB 43.9 MB/s 
     |████████████████████████████████| 54 kB 3.3 MB/s 
     |████████████████████████████████| 56 kB 4.8 MB/s 
     |████████████████████████████████| 63 kB 2.2 MB/s 
     |████████████████████████████████| 80 kB 9.5 MB/s 
     |████████████████████████████████| 68 kB 7.3 MB/s 
     |████████████████████████████████| 46 kB 4.1 MB/s 
     |████████████████████████████████| 4.0 MB 60.3 MB/s 
     |████████████████████████████████| 856 kB 55.

In [ ]:
import pickle
import re
import gradio as gr
import sklearn
#from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import StratifiedShuffleSplit
import stanza
stanza.download('mr')
nlp = stanza.Pipeline('mr', processors='tokenize,pos,lemma,ner,mwt', verbose=True, use_gpu=True)

filename = 'classifier.pkl'
classifier = pickle.load(open(filename, 'rb'))
vectorizer = pickle.load(open("vectorizer.pickle", "rb"))
def clean(text):
  text_lemma = []
  doc = nlp(text)
  lemma = []
  for sentence in doc.sentences:
      for word in sentence.words:
          text_lemma.append(word.lemma)
  text_lemma = " ".join(word for word in text_lemma)
  return text_lemma

def checker(input_text):
    transform = {}
    input_text = [input_text]
    input_text[0] = clean(input_text[0])
    transform['cleaned'] = input_text[0]
    input_text = vectorizer.transform(input_text)
    transform['vectorized'] = input_text
    prediction = classifier.predict(input_text)
    print(prediction)
    return prediction

output_text = gr.outputs.Textbox(label="Result")
gr.Interface(checker, "textbox", outputs=['text'], title="Text Classification in Marathi Language").launch(debug=True)

INFO:stanza:Downloading default packages for language: mr (Marathi) ...


INFO:stanza:Finished downloading models and saved to /root/stanza_resources.
INFO:stanza:Checking for updates to resources.json in case models have been updated.  Note: this behavior can be turned off with download_method=None or download_method=DownloadMethod.REUSE_RESOURCES


INFO:stanza:Loading these models for language: mr (Marathi):
| Processor | Package |
-----------------------
| tokenize  | ufal    |
| mwt       | ufal    |
| pos       | ufal    |
| lemma     | ufal    |
| ner       | l3cube  |

INFO:stanza:Use device: cpu
INFO:stanza:Loading: tokenize
INFO:stanza:Loading: mwt
INFO:stanza:Loading: pos
INFO:stanza:Loading: lemma
INFO:stanza:Loading: ner
INFO:stanza:Done loading processors!
/usr/local/lib/python3.7/dist-packages/gradio/outputs.py:22: UserWarning: Usage of gradio.outputs is deprecated, and will not be supported in the future, please import your components from gradio.components
  "Usage of gradio.outputs is deprecated, and will not be supported in the future, please import your components from gradio.components",
/usr/local/lib/python3.7/dist-packages/gradio/deprecation.py:40: UserWarning: The 'type' parameter has been deprecated. Use the Number component instead.
  warnings.warn(value)


Colab notebook detected. This cell will run indefinitely so that you can see errors and logs. To turn off, set debug=False in launch().
Running on public URL: https://15285642e74ac537.gradio.app

This share link expires in 72 hours. For free permanent hosting and GPU upgrades (NEW!), check out Spaces: https://huggingface.co/spaces


['sports']
['entertainment']
